version: '3.8'

services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "8000:8000"
    environment:
      # - NODE_ENV=development
      - PORT=8000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - todo-network
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - todo-network
    stdin_open: true
    tty: true
    command: npm start

networks:
  todo-network:
    driver: bridge
